server:
  port: 8080
spring:
  application:
    name: padel-global-score
  mvc:
    servlet:
      path: /api
    throw-exception-if-no-handler-found: true # Para manejar errores 404
  web:
    resources:
      add-mappings: false # Desactiva el manejo automatico de recursos estaticos
  
  # Conexion a la base de datos
  datasource:
    url: jdbc:postgresql://localhost:5433/padel_db
    username: app-user
    password: app-pass123
    driver-class-name: org.postgresql.Driver

  # Configuracion JPA/Hibernate
  jpa:
    hibernate.ddl-auto: update #create-drop  # Sirve para validar el esquema de la base de datos.
    show-sql: true # En produccion se desactiva.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

timezone: "America/Argentina/Buenos_Aires"


